/**
 * Every editable text on the invitation, grouped as it appears on the page.
 *
 * `key` must match the data-content marker in index.html. Adding a field here
 * and marking the element is all that is needed - the storage is key/value, so
 * no migration or API change is involved.
 *
 * type: 'text' (single line) | 'area' (multi line) | 'datetime'
 */
export const contentFields = [
    {
        group: 'Couple',
        icon: 'fa-heart',
        fields: [
            { key: 'couple_display', label: 'Couple (shown on the cover)', type: 'text' },
            { key: 'groom_name', label: 'Groom full name', type: 'text' },
            { key: 'groom_role', label: 'Groom description', type: 'text', hint: 'e.g. First Son' },
            { key: 'groom_father', label: 'Groom father', type: 'text' },
            { key: 'groom_mother', label: 'Groom mother', type: 'text' },
            { key: 'bride_name', label: 'Bride full name', type: 'text' },
            { key: 'bride_role', label: 'Bride description', type: 'text', hint: 'e.g. Second Daughter' },
            { key: 'bride_father', label: 'Bride father', type: 'text' },
            { key: 'bride_mother', label: 'Bride mother', type: 'text' },
        ],
    },
    {
        group: 'Date & Venue',
        icon: 'fa-calendar-day',
        fields: [
            {
                key: 'event_datetime',
                label: 'Wedding date & time',
                type: 'datetime',
                hint: 'Drives the countdown, the printed date and the calendar button.',
            },
            {
                key: 'event_date_text',
                label: 'Printed date (optional)',
                type: 'text',
                hint: 'Leave empty to write it out automatically from the date above.',
            },
            {
                key: 'countdown_days',
                label: 'Countdown: days',
                type: 'text',
                hint: 'Shown next to the number of days. Clear it to show the number on its own.',
            },
            {
                key: 'countdown_hours',
                label: 'Countdown: hours',
                type: 'text',
                hint: 'The clock shows 22:45:04, so these three are read aloud by screen readers only.',
            },
            { key: 'countdown_minutes', label: 'Countdown: minutes', type: 'text' },
            { key: 'countdown_seconds', label: 'Countdown: seconds', type: 'text' },
            { key: 'ceremony_intro', label: 'Ceremony intro line', type: 'area' },
            { key: 'akad_heading', label: 'Ceremony title', type: 'text' },
            { key: 'akad_time', label: 'Ceremony time', type: 'text' },
            { key: 'resepsi_heading', label: 'Reception title', type: 'text' },
            { key: 'resepsi_time', label: 'Reception time', type: 'text' },
            { key: 'venue_address', label: 'Venue address', type: 'area' },
            { key: 'dresscode_intro', label: 'Dress code intro', type: 'area' },
            { key: 'dresscode_text', label: 'Dress code', type: 'text' },
        ],
    },
    {
        group: 'Greetings & Verses',
        icon: 'fa-star-and-crescent',
        fields: [
            { key: 'home_heading', label: 'Cover heading', type: 'text' },
            { key: 'bismillah', label: 'Opening (Arabic)', type: 'text' },
            { key: 'greeting_open', label: 'Opening greeting', type: 'text' },
            { key: 'invite_line', label: 'Invitation line', type: 'area' },
            { key: 'quran_heading', label: 'Verse section heading', type: 'text' },
            { key: 'quran_1_text', label: 'Verse 1', type: 'area' },
            { key: 'quran_1_ref', label: 'Verse 1 reference', type: 'text' },
            { key: 'quran_2_text', label: 'Verse 2', type: 'area' },
            { key: 'quran_2_ref', label: 'Verse 2 reference', type: 'text' },
            { key: 'closing_arabic', label: 'Closing (Arabic)', type: 'text' },
            { key: 'closing_greeting', label: 'Closing greeting', type: 'text' },
        ],
    },
    {
        group: 'Love Story',
        icon: 'fa-book-open',
        fields: [
            { key: 'story_heading', label: 'Section heading', type: 'text' },
            { key: 'story_button', label: 'Open story button', type: 'text' },
            { key: 'story_1', label: 'Paragraph 1', type: 'area' },
            { key: 'story_2', label: 'Paragraph 2', type: 'area' },
            { key: 'story_3', label: 'Paragraph 3', type: 'area' },
        ],
    },
    {
        group: 'Gift',
        icon: 'fa-gift',
        fields: [
            { key: 'gift_heading', label: 'Section heading', type: 'text' },
            { key: 'gift_intro', label: 'Intro line', type: 'area', hint: 'The sentence above the payment options.' },
            { key: 'gift_1_label', label: 'Payment option 1 label', type: 'text', hint: 'e.g. Bank Transfer' },
            { key: 'gift_1_name', label: 'Bank account holder', type: 'text' },
            { key: 'gift_bank_name', label: 'Bank name', type: 'text' },
            { key: 'gift_account', label: 'Account number', type: 'text' },
            { key: 'gift_2_label', label: 'Payment option 2 label', type: 'text', hint: 'e.g. E-wallet' },
            { key: 'gift_2_name', label: 'E-wallet name', type: 'text' },
            { key: 'gift_3_label', label: 'Payment option 3 label', type: 'text', hint: 'e.g. Gift' },
            { key: 'gift_3_name', label: 'Gift recipient', type: 'text' },
            { key: 'gift_phone', label: 'Contact phone', type: 'text' },
            { key: 'gift_details', label: 'Details button', type: 'text' },
        ],
    },
    {
        group: 'Welcome & Buttons',
        icon: 'fa-envelope-open',
        fields: [
            { key: 'welcome_message', label: 'Greeting above the guest name', type: 'text', hint: 'Shown on the envelope, e.g. "To the Honorable Mr./Mrs."' },
            { key: 'envelope_prompt', label: 'Envelope: tap hint', type: 'text', hint: 'Under the wax seal, e.g. "Tap the seal to open".' },
            { key: 'envelope_monogram', label: 'Envelope: seal monogram', type: 'text', hint: 'The mark stamped into the wax. One or two characters work best - an "&", or your initials.' },
            { key: 'envelope_skip', label: 'Envelope: skip link', type: 'text', hint: 'Top corner, for anyone who would rather go straight in.' },
            { key: 'maps_label', label: 'Maps button label', type: 'text' },
            { key: 'maps_url', label: 'Google Maps link', type: 'text', hint: 'Full https:// link to the venue.' },
            { key: 'closing_thanks', label: 'Closing thank you', type: 'area' },
        ],
    },
    {
        group: 'RSVP',
        icon: 'fa-envelope-circle-check',
        fields: [
            { key: 'rsvp_heading', label: 'RSVP heading', type: 'text' },
            { key: 'rsvp_dear', label: 'Word before the guest name', type: 'text' },
            { key: 'rsvp_accept', label: 'Accept button', type: 'text' },
            { key: 'rsvp_decline', label: 'Decline button', type: 'text' },
            { key: 'rsvp_count_label', label: 'Headcount question', type: 'text' },
            { key: 'rsvp_submit', label: 'Send response button', type: 'text' },
            { key: 'rsvp_change_button', label: 'Change answer button', type: 'text' },
            { key: 'rsvp_choose_warning', label: 'Warning when no answer picked', type: 'text' },
            { key: 'rsvp_thanks', label: 'Message after answering', type: 'text' },
            { key: 'rsvp_seats_note', label: 'Party size note', type: 'text', hint: 'Use {count} for the number of seats.' },
            { key: 'rsvp_deadline_note', label: 'Reply-by note', type: 'area', hint: 'Use {date} for the deadline.' },
            { key: 'rsvp_closed_note', label: 'Replies closed note', type: 'text', hint: 'Use {date} for the deadline.' },
            { key: 'rsvp_accepted', label: 'Confirmation, one guest', type: 'area' },
            { key: 'rsvp_accepted_many', label: 'Confirmation, several guests', type: 'area', hint: 'Use {count} for how many are coming.' },
            { key: 'rsvp_declined', label: 'Confirmation, not attending', type: 'area' },
            { key: 'rsvp_closed_message', label: 'Message after the deadline', type: 'area' },
        ],
    },
    {
        group: 'Other Headings',
        icon: 'fa-heading',
        fields: [
            { key: 'welcome_heading', label: 'Welcome screen heading', type: 'text' },
            { key: 'moment_heading', label: 'Moment section heading', type: 'text' },
            { key: 'gallery_heading', label: 'Gallery heading', type: 'text' },
            { key: 'wishes_heading', label: 'Wishes heading', type: 'text' },
            { key: 'calendar_title', label: 'Calendar event title', type: 'text', hint: 'Defaults to "The Wedding of <couple>".' },
            { key: 'calendar_details', label: 'Calendar description', type: 'area' },
        ],
    },
    {
        group: 'Bottom Menu',
        icon: 'fa-bars',
        fields: [
            { key: 'nav_home', label: 'Home', type: 'text' },
            { key: 'nav_couple', label: 'Couple', type: 'text' },
            { key: 'nav_date', label: 'Date', type: 'text' },
            { key: 'nav_gallery', label: 'Gallery', type: 'text' },
            { key: 'nav_rsvp', label: 'RSVP', type: 'text', hint: 'Only shown to guests with a personal link.' },
            { key: 'nav_wishes', label: 'Wishes', type: 'text' },
            { key: 'nav_music', label: 'Music', type: 'text' },
        ],
    },
    {
        group: 'Comment Form',
        icon: 'fa-comments',
        fields: [
            { key: 'comment_name_label', label: 'Name label', type: 'text' },
            { key: 'comment_name_placeholder', label: 'Name placeholder', type: 'text' },
            { key: 'comment_presence_label', label: 'Attendance label', type: 'text' },
            { key: 'comment_presence_default', label: 'Attendance: default option', type: 'text' },
            { key: 'comment_presence_yes', label: 'Attendance: attending option', type: 'text' },
            { key: 'comment_presence_no', label: 'Attendance: not attending option', type: 'text' },
            { key: 'comment_label', label: 'Wishes form label', type: 'text' },
            { key: 'comment_placeholder', label: 'Wishes box placeholder', type: 'text' },
            { key: 'comment_send', label: 'Send button', type: 'text' },
            { key: 'comment_reply', label: 'Reply button', type: 'text' },
            { key: 'comment_edit', label: 'Edit button', type: 'text' },
            { key: 'comment_delete', label: 'Delete button', type: 'text' },
            { key: 'comment_cancel', label: 'Cancel button', type: 'text' },
            { key: 'comment_update', label: 'Update button', type: 'text' },
            { key: 'comment_reply_placeholder', label: 'Reply box placeholder', type: 'text' },
            { key: 'comment_update_placeholder', label: 'Edit box placeholder', type: 'text' },
            { key: 'gif_label', label: 'GIF label', type: 'text' },
            { key: 'gif_search_placeholder', label: 'GIF search placeholder', type: 'text' },
            { key: 'pagination_prev', label: 'Pagination: previous', type: 'text' },
            { key: 'pagination_next', label: 'Pagination: next', type: 'text' },
        ],
    },
    {
        group: 'Interface & Loading',
        icon: 'fa-mobile-screen',
        fields: [
            { key: 'page_title', label: 'Browser tab title', type: 'text' },
            { key: 'add_to_calendar', label: 'Add to Calendar button', type: 'text' },
            { key: 'scroll_down', label: 'Scroll Down hint', type: 'text' },
            { key: 'loading_text', label: 'Loading text', type: 'text' },
            { key: 'noscript_message', label: 'No-JavaScript message', type: 'text' },
            { key: 'carousel_prev', label: 'Carousel: previous', type: 'text', hint: 'Read by screen readers on gallery arrows.' },
            { key: 'carousel_next', label: 'Carousel: next', type: 'text', hint: 'Read by screen readers on gallery arrows.' },
        ],
    },
];
